### ISSUE TITLE
why comment out the adversarial learning loss about the shared features?

### ISSUE THREAD

**Issue by xuyingxiao** [MiaoHaoSunny/MT-ASTN#1]
Hi, you noticed the adversarial learning about the shared features in the paper. But the diff_loss is commented out in the train.py, why? What difference does it make with or without adversarial learning?

**Comment by MiaoHaoSunny** [comment]
Sorry, I have uploaded the wrong code. I will fix it soon. Thanks for your reminding.

**Comment by MiaoHaoSunny** [comment]
The code could be a little messy. And I don't check it carefully. Now, I modify the train.py. If you have furthe problem, pls send email to me(haomiao96@gmail.com). I will reply as soon as possible. The performance of our model will be improved by adding adversarial learning. You can find it from our paper.

**Comment by MiaoHaoSunny** [comment]
Good question.
